"""Turning an attachment's bytes into text a language model can actually read.

Deliberately separate from gmail_tools: nothing here knows about Gmail, mailboxes
or tokens, which keeps every converter a pure bytes -> str function that can be
tested against a file built in the test itself.

Dispatch is on the FILENAME EXTENSION, not the MIME type. Mail clients are
careless about Content-Type - a spreadsheet forwarded through a phone routinely
arrives as application/octet-stream - so the extension is the more reliable
signal in practice. The MIME type is only a fallback when there is no extension.
"""

import csv
import io
import logging
import zipfile

logger = logging.getLogger(__name__)

# The worker on Render's free tier has limited memory, and every converter below
# holds the whole file plus its parsed form at once. Refuse early and clearly
# rather than being killed mid-parse, which looks to the user like a silent hang.
MAX_ATTACHMENT_BYTES = 5 * 1024 * 1024

# One page of a plain read. The extracted text is injected into the Gemini prompt
# and costs money and context on every later message, so a whole spreadsheet
# cannot go in at once - but nothing is unreachable either: read_email_attachment
# takes a part number and iter_rows/search below scan the file with no cap at all.
MAX_TEXT_CHARS = 15000

# Extraction assembles the whole file in memory before paging it. Render's free
# worker has ~512MB and is killed silently when it runs out, which reads to the
# user as a hang rather than as an error - so the assembly stops here. Search
# does not go through this path; it streams and never holds the file.
MAX_EXTRACT_CHARS = 2_000_000

# Every row of every sheet is scanned. These bound only how much is echoed back.
MAX_MATCHES_RETURNED = 300
MAX_SEARCH_OUTPUT_CHARS = 12000


def _page(text: str, part: int) -> str:
    """Splits a long extraction into numbered pages on line boundaries.

    Paging rather than truncating: the previous version cut the file off and
    offered no way to ask for the rest, so data past the cut was simply
    unreachable however the question was phrased."""
    text = text.strip()
    if len(text) <= MAX_TEXT_CHARS:
        return text

    pages, current = [], ""
    for line in text.split("\n"):
        # A single line longer than a page is split mid-line - rare, and better
        # than emitting a page that busts the budget.
        while len(line) > MAX_TEXT_CHARS:
            if current:
                pages.append(current)
                current = ""
            pages.append(line[:MAX_TEXT_CHARS])
            line = line[MAX_TEXT_CHARS:]
        if len(current) + len(line) + 1 > MAX_TEXT_CHARS:
            pages.append(current)
            current = line
        else:
            current = f"{current}\n{line}" if current else line
    if current:
        pages.append(current)

    total = len(pages)
    index = max(1, min(part, total))
    header = f"[חלק {index} מתוך {total}]"
    if index < total:
        footer = (
            f"\n\n[סוף חלק {index}. יש עוד {total - index} חלקים - "
            f"אפשר לבקש את חלק {index + 1}.]"
        )
    else:
        footer = f"\n\n[זה החלק האחרון ({total} מתוך {total}). הקובץ נקרא במלואו.]"
    return f"{header}\n{pages[index - 1]}{footer}"


def _decode(raw: bytes) -> str:
    """Hebrew mail attachments are usually UTF-8 but Windows-authored CSVs are
    often cp1255, and a wrong guess yields mojibake rather than an error."""
    for encoding in ("utf-8-sig", "utf-8", "cp1255", "iso-8859-8"):
        try:
            return raw.decode(encoding)
        except UnicodeDecodeError:
            continue
    return raw.decode("utf-8", errors="replace")


def _cells_to_row(values) -> str:
    cells = ["" if v is None else str(v).strip() for v in values]
    return " | ".join(cells) if any(cells) else ""


def _rows_plain_text(raw: bytes):
    for number, line in enumerate(_decode(raw).splitlines(), start=1):
        if line.strip():
            yield "", number, line.strip()


def _rows_delimited(raw: bytes):
    text = _decode(raw)
    # Sniffing beats assuming a comma: exports from Hebrew Excel are frequently
    # semicolon-separated, which would otherwise come out as one column.
    sample = text[:4000]
    try:
        delimiter = csv.Sniffer().sniff(sample, delimiters=",;\t|").delimiter
    except csv.Error:
        delimiter = ","
    for number, values in enumerate(csv.reader(io.StringIO(text), delimiter=delimiter), start=1):
        row = _cells_to_row(values)
        if row:
            yield "", number, row


def _rows_xlsx(raw: bytes):
    from openpyxl import load_workbook

    # read_only streams the sheet instead of building the whole object graph,
    # which is what lets a large workbook be scanned end to end on a small worker.
    #
    # data_only=True returns the values Excel cached, not the formulas. A file
    # generated by a script and never opened in Excel has no cached values, so
    # formula cells come back empty - that is a property of the file, not a bug.
    workbook = load_workbook(io.BytesIO(raw), read_only=True, data_only=True)
    try:
        for sheet in workbook.worksheets:
            for number, values in enumerate(sheet.iter_rows(values_only=True), start=1):
                row = _cells_to_row(values)
                if row:
                    yield sheet.title, number, row
    finally:
        workbook.close()


def _rows_docx(raw: bytes):
    import docx

    document = docx.Document(io.BytesIO(raw))
    number = 0
    for paragraph in document.paragraphs:
        if paragraph.text.strip():
            number += 1
            yield "", number, paragraph.text.strip()
    # Tables are a separate tree in the docx model; a document whose content is
    # mostly a table would otherwise come back almost empty.
    for table in document.tables:
        for row in table.rows:
            line = _cells_to_row([c.text for c in row.cells])
            if line:
                number += 1
                yield "", number, line


def _rows_pdf(raw: bytes):
    from pypdf import PdfReader

    reader = PdfReader(io.BytesIO(raw))
    for page_number, page in enumerate(reader.pages, start=1):
        text = (page.extract_text() or "").strip()
        if not text:
            continue
        for line_number, line in enumerate(text.splitlines(), start=1):
            if line.strip():
                yield f"עמוד {page_number}", line_number, line.strip()


_READERS = {
    ".txt": _rows_plain_text, ".md": _rows_plain_text, ".json": _rows_plain_text,
    ".log": _rows_plain_text, ".xml": _rows_plain_text, ".html": _rows_plain_text,
    ".csv": _rows_delimited, ".tsv": _rows_delimited,
    ".xlsx": _rows_xlsx, ".xlsm": _rows_xlsx,
    ".docx": _rows_docx,
    ".pdf": _rows_pdf,
}

# Named so the assistant can explain the limit instead of reporting a failure.
_KNOWN_UNSUPPORTED = {
    ".xls": "פורמט Excel ישן (xls). צריך לשמור אותו מחדש כ-xlsx כדי שאוכל לקרוא.",
    ".doc": "פורמט Word ישן (doc). צריך לשמור אותו מחדש כ-docx כדי שאוכל לקרוא.",
    ".ppt": "מצגת PowerPoint - קריאת מצגות לא נתמכת.",
    ".pptx": "מצגת PowerPoint - קריאת מצגות לא נתמכת.",
    ".zip": "קובץ ZIP - צריך לחלץ אותו קודם.",
    ".rar": "קובץ RAR - צריך לחלץ אותו קודם.",
    ".jpg": "תמונה. אני קורא טקסט בלבד, לא מנתח תמונות.",
    ".jpeg": "תמונה. אני קורא טקסט בלבד, לא מנתח תמונות.",
    ".png": "תמונה. אני קורא טקסט בלבד, לא מנתח תמונות.",
    ".heic": "תמונה. אני קורא טקסט בלבד, לא מנתח תמונות.",
    ".gif": "תמונה. אני קורא טקסט בלבד, לא מנתח תמונות.",
}


def _extension(filename: str) -> str:
    _, dot, ext = filename.rpartition(".")
    return f".{ext.lower()}" if dot else ""


def supported_extensions() -> list:
    return sorted(_READERS)


def is_supported(filename: str, mime_type: str = "") -> bool:
    """Whether extract_text can read this file, judged from its name alone.

    Needed before the bytes exist: read_email lists what is attached without
    downloading anything, and has to say which ones are worth asking for."""
    ext = _extension(filename)
    if ext in _READERS:
        return True
    if not ext and mime_type:
        return mime_type.startswith("text/") or mime_type == "application/pdf"
    return False


def _resolve_reader(filename: str, mime_type: str):
    """Returns (reader, error). Exactly one of the two is None."""
    ext = _extension(filename)
    reader = _READERS.get(ext)

    if reader is None and not ext and mime_type:
        # No extension to go on - fall back to the declared type, which is the
        # only remaining signal.
        if mime_type.startswith("text/"):
            reader = _rows_plain_text
        elif mime_type == "application/pdf":
            reader = _rows_pdf

    if reader is not None:
        return reader, None
    if ext in _KNOWN_UNSUPPORTED:
        return None, f"❌ {_KNOWN_UNSUPPORTED[ext]}"
    return None, (
        f"❌ סוג הקובץ {ext or mime_type or 'לא ידוע'} אינו נתמך לקריאה. "
        f"נתמכים: {', '.join(supported_extensions())}"
    )


def _size_error(raw: bytes):
    if not raw:
        return "❌ הקובץ ריק."
    if len(raw) > MAX_ATTACHMENT_BYTES:
        size_mb = len(raw) / (1024 * 1024)
        return (
            f"❌ הקובץ גדול מדי לקריאה ({size_mb:.1f}MB, המגבלה "
            f"{MAX_ATTACHMENT_BYTES // (1024 * 1024)}MB)."
        )
    return None


def iter_rows(filename: str, raw: bytes, mime_type: str = ""):
    """Streams the file as (section, row_number, text) with no limit on length.

    Search runs on this, so scanning is bounded by the file, not by a cap: the
    whole workbook is examined however many rows it has. Nothing is accumulated,
    which is what keeps a large file from exhausting the worker's memory."""
    reader, error = _resolve_reader(filename, mime_type)
    if reader is None:
        raise ValueError(error)
    return reader(raw)


def extract_text(filename: str, raw: bytes, mime_type: str = "", part: int = 1) -> str:
    """Converts one attachment's bytes to text, or explains why it cannot.

    Long files come back in numbered parts rather than cut off: pass part=2 for
    the next slice. Always returns a string - callers surface it to the user
    as-is, so a failure has to read as an explanation rather than as a stack
    trace or as silence."""
    error = _size_error(raw)
    if error:
        return error
    reader, error = _resolve_reader(filename, mime_type)
    if reader is None:
        return error

    try:
        chunks, section, length, capped = [], None, 0, False
        for row_section, _, row in reader(raw):
            if row_section != section:
                section = row_section
                if section:
                    heading = f"\n--- {section} ---"
                    chunks.append(heading)
                    length += len(heading) + 1
            chunks.append(row)
            length += len(row) + 1
            if length > MAX_EXTRACT_CHARS:
                capped = True
                break
        text = "\n".join(chunks)
    except zipfile.BadZipFile:
        # xlsx and docx are both zip containers; a corrupted or mislabelled file
        # fails here rather than anywhere more informative.
        return "❌ הקובץ פגום או שסיומת הקובץ לא תואמת לתוכן שלו."
    except Exception as e:
        logger.error(f"Attachment parse failed for {filename!r}: {e}")
        return f"❌ לא הצלחתי לפענח את הקובץ: {e}"

    if not text.strip():
        if reader is _rows_pdf:
            # A scanned document is an image inside a PDF wrapper. Saying "empty"
            # would be misleading - there is content, it just is not text.
            return (
                "ה-PDF לא מכיל טקסט שניתן לחלץ. סביר שזה מסמך סרוק (תמונה), "
                "וקריאה שלו תדרוש OCR שלא מותקן כאן."
            )
        return "הקובץ נקרא בהצלחה אך אין בו טקסט."

    paged = _page(text, part)
    if capped:
        paged += (
            "\n[הקובץ ארוך במיוחד ולא נטען כולו לזיכרון. "
            "כדי למצוא שורות מסוימות עדיף לחפש בו לפי מילות מפתח - החיפוש סורק הכול.]"
        )
    return paged


# --- Searching inside an attachment -------------------------------------------
#
# Reading a whole file into the prompt is the wrong tool for "which rows mention
# Ramla and me": it costs the whole file in tokens and still gets paged. Search
# streams every row, matches in Python, and returns only the hits - so the scan
# has no ceiling at all while the answer stays small.

# Hebrew makes naive substring matching wrong in both directions. Spelling is not
# stable across writers - כתיב מלא vs חסר turns קריית into קרית - and abbreviations
# carry gershayim that may be the Hebrew mark or an ASCII quote. Normalising both
# sides collapses those differences instead of requiring the file to be tidy.
_HEBREW_MARKS = str.maketrans({
    "׳": "", "״": "", "'": "", '"': "", "’": "", "“": "", "”": "",
    "־": " ", "-": " ", "_": " ", "/": " ", "\\": " ", ",": " ", ".": " ",
    "(": " ", ")": " ", "[": " ", "]": " ", ":": " ", ";": " ", "|": " ",
})
_FINAL_LETTERS = str.maketrans({"ך": "כ", "ם": "מ", "ן": "נ", "ף": "פ", "ץ": "צ"})


def _normalise(text: str) -> str:
    text = text.lower().translate(_HEBREW_MARKS).translate(_FINAL_LETTERS)
    # Niqqud and cantillation carry no meaning for a name match and would only
    # break equality between two spellings of the same word.
    text = "".join(c for c in text if not "֑" <= c <= "ׇ")
    # כתיב מלא vs חסר: קריית -> קרית, ראשון -> ראשנ? no - only doubled letters.
    while "יי" in text:
        text = text.replace("יי", "י")
    while "וו" in text:
        text = text.replace("וו", "ו")
    return " ".join(text.split())


def _tokens(text: str) -> list:
    return _normalise(text).split()


# Itai's territory, as he listed it. Each entry maps one city to the spellings a
# real file actually uses - Hebrew full and defective, the common abbreviation,
# and the English transliterations, which vary by whoever typed the export.
CITY_ALIASES = {
    "ראשון לציון": ["ראשון לציון", "ראשל צ", "רשל צ", "ראשלצ", "רשלצ",
                    "rishon lezion", "rishon letzion", "rishon le zion", "rishon"],
    "רמלה": ["רמלה", "ramla", "ramle", "ramleh"],
    "לוד": ["לוד", "lod", "lydda"],
    "קריית אונו": ["קריית אונו", "קרית אונו", "kiryat ono", "qiryat ono", "kyriat ono"],
    "קריית עקרון": ["קריית עקרון", "קרית עקרון", "kiryat ekron", "kiryat akron",
                    "qiryat eqron", "kiryat ackron"],
    "יבנה": ["יבנה", "yavne", "yavneh", "javne"],
    "אור יהודה": ["אור יהודה", "or yehuda", "or yehuda", "or yehudah"],
}


def expand_keyword(keyword: str) -> list:
    """Returns every spelling worth trying for one search term.

    A city the user names in Hebrew has to match its English column too, and vice
    versa, because a single export mixes both."""
    normalised = _normalise(keyword)
    if not normalised:
        return []
    for city, aliases in CITY_ALIASES.items():
        for alias in aliases:
            if _normalise(alias) == normalised:
                return [_normalise(a) for a in aliases if _normalise(a)]
    return [normalised]


def _matches(row_tokens: list, needle_tokens: list) -> bool:
    """True when the needle appears as a run of whole tokens in the row.

    Whole tokens rather than a substring: 'לוד' is three letters and would
    otherwise match inside unrelated words, and 'Lod' would match 'Lodging'.
    Running over tokens also makes a two-word city like 'אור יהודה' match even
    when the cell wraps it in other text."""
    if not needle_tokens:
        return False
    span = len(needle_tokens)
    return any(
        row_tokens[i:i + span] == needle_tokens
        for i in range(len(row_tokens) - span + 1)
    )


def _split_terms(raw) -> list:
    if raw is None:
        return []
    if isinstance(raw, (list, tuple)):
        items = list(raw)
    else:
        # The model sends one string; commas and newlines are how a person lists
        # things, so both separate terms.
        items = str(raw).replace("\n", ",").split(",")
    return [t.strip() for t in items if str(t).strip()]


def _group(terms: list) -> list:
    """One search group: a list of alternative token-lists, any of which matches."""
    expanded = []
    for term in terms:
        for spelling in expand_keyword(term):
            tokens = spelling.split()
            if tokens and tokens not in expanded:
                expanded.append(tokens)
    return expanded


def search(filename: str, raw: bytes, keywords, must_also_match=None,
           mime_type: str = "") -> str:
    """Scans every row of the file and returns the ones that match.

    keywords match on OR. must_also_match is a second OR group ANDed with the
    first, which is what "Ramla or Lod, but only my rows or Nikita's" needs -
    two independent lists rather than one flat list of terms.
    """
    error = _size_error(raw)
    if error:
        return error

    primary = _group(_split_terms(keywords))
    if not primary:
        return "❌ לא נמסרו מילות חיפוש."
    secondary = _group(_split_terms(must_also_match))

    try:
        rows = iter_rows(filename, raw, mime_type)
    except ValueError as e:
        return str(e)

    matches, scanned, truncated = [], 0, False
    try:
        for section, number, row in rows:
            scanned += 1
            tokens = _tokens(row)
            if not any(_matches(tokens, n) for n in primary):
                continue
            if secondary and not any(_matches(tokens, n) for n in secondary):
                continue
            if len(matches) >= MAX_MATCHES_RETURNED:
                truncated = True
                # Keep scanning: the total is worth reporting accurately even
                # when not every hit can be shown.
                continue
            matches.append((section, number, row))
    except zipfile.BadZipFile:
        return "❌ הקובץ פגום או שסיומת הקובץ לא תואמת לתוכן שלו."
    except Exception as e:
        logger.error(f"Attachment search failed for {filename!r}: {e}")
        return f"❌ לא הצלחתי לפענח את הקובץ: {e}"

    terms_text = ", ".join(_split_terms(keywords))
    also_text = ", ".join(_split_terms(must_also_match))
    criteria = f"'{terms_text}'" + (f" יחד עם '{also_text}'" if also_text else "")

    if not matches:
        return (
            f"סרקתי את כל הקובץ {filename} ({scanned:,} שורות) ולא נמצאה אף שורה "
            f"שמתאימה ל-{criteria}."
        )

    lines, section = [], None
    for row_section, number, row in matches:
        if row_section != section:
            section = row_section
            if section:
                lines.append(f"--- {section} ---")
        lines.append(f"{number}: {row}")
    body = "\n".join(lines)
    if len(body) > MAX_SEARCH_OUTPUT_CHARS:
        body = body[:MAX_SEARCH_OUTPUT_CHARS] + "\n[...]"
        truncated = True

    total = len(matches) + (1 if truncated else 0)
    header = (
        f"🔎 חיפוש ב-{filename}: נסרקו כל {scanned:,} השורות, "
        f"נמצאו {len(matches)} שורות שמתאימות ל-{criteria}."
    )
    if truncated:
        header += f" (מוצגות הראשונות; יש עוד - כדאי לצמצם את החיפוש.)"
    return f"{header}\n\n{body}"
