"""Turning an attachment's bytes into text a language model can actually read.

Deliberately separate from gmail_tools: nothing here knows about Gmail, mailboxes
or tokens, which keeps every converter a pure bytes -> str function that can be
tested against a file built in the test itself.

Dispatch is on the FILENAME EXTENSION, not the MIME type. Mail clients are
careless about Content-Type - a spreadsheet forwarded through a phone routinely
arrives as application/octet-stream - so the extension is the more reliable
signal in practice. The MIME type is only a fallback when there is no extension.
"""

import csv
import io
import logging
import zipfile

logger = logging.getLogger(__name__)

# The worker on Render's free tier has limited memory, and every converter below
# holds the whole file plus its parsed form at once. Refuse early and clearly
# rather than being killed mid-parse, which looks to the user like a silent hang.
MAX_ATTACHMENT_BYTES = 5 * 1024 * 1024

# The extracted text is injected into the Gemini prompt, so it costs money and
# context on every subsequent message in the conversation. A spreadsheet of a few
# thousand rows would swamp both.
MAX_TEXT_CHARS = 6000
MAX_ROWS_PER_SHEET = 200
MAX_PDF_PAGES = 30

_TRUNCATION_NOTE = "\n[...הקובץ ארוך מכדי להיקרא במלואו, זה החלק הראשון שלו]"


def _truncate(text: str) -> str:
    text = text.strip()
    if len(text) > MAX_TEXT_CHARS:
        return text[:MAX_TEXT_CHARS] + _TRUNCATION_NOTE
    return text


def _decode(raw: bytes) -> str:
    """Hebrew mail attachments are usually UTF-8 but Windows-authored CSVs are
    often cp1255, and a wrong guess yields mojibake rather than an error."""
    for encoding in ("utf-8-sig", "utf-8", "cp1255", "iso-8859-8"):
        try:
            return raw.decode(encoding)
        except UnicodeDecodeError:
            continue
    return raw.decode("utf-8", errors="replace")


def _read_plain_text(raw: bytes) -> str:
    return _decode(raw)


def _read_delimited(raw: bytes) -> str:
    text = _decode(raw)
    # Sniffing beats assuming a comma: exports from Hebrew Excel are frequently
    # semicolon-separated, which would otherwise come out as one column.
    sample = text[:4000]
    try:
        delimiter = csv.Sniffer().sniff(sample, delimiters=",;\t|").delimiter
    except csv.Error:
        delimiter = ","
    rows = list(csv.reader(io.StringIO(text), delimiter=delimiter))
    lines = [" | ".join(cell.strip() for cell in row) for row in rows if any(c.strip() for c in row)]
    return "\n".join(lines)


def _read_xlsx(raw: bytes) -> str:
    from openpyxl import load_workbook

    # data_only=True returns the values Excel cached, not the formulas. A file
    # generated by a script and never opened in Excel has no cached values, so
    # formula cells come back empty - that is a property of the file, not a bug.
    workbook = load_workbook(io.BytesIO(raw), read_only=True, data_only=True)
    try:
        chunks = []
        for sheet in workbook.worksheets:
            lines = []
            for index, row in enumerate(sheet.iter_rows(values_only=True)):
                if index >= MAX_ROWS_PER_SHEET:
                    lines.append(f"[...עוד שורות בגיליון, הוצגו {MAX_ROWS_PER_SHEET} הראשונות]")
                    break
                cells = ["" if value is None else str(value).strip() for value in row]
                if any(cells):
                    lines.append(" | ".join(cells))
            if lines:
                chunks.append(f"--- גיליון: {sheet.title} ---\n" + "\n".join(lines))
        return "\n\n".join(chunks)
    finally:
        workbook.close()


def _read_docx(raw: bytes) -> str:
    import docx

    document = docx.Document(io.BytesIO(raw))
    parts = [p.text.strip() for p in document.paragraphs if p.text.strip()]
    # Tables are a separate tree in the docx model; a document whose content is
    # mostly a table would otherwise come back almost empty.
    for table in document.tables:
        for row in table.rows:
            cells = [c.text.strip() for c in row.cells]
            if any(cells):
                parts.append(" | ".join(cells))
    return "\n".join(parts)


def _read_pdf(raw: bytes) -> str:
    from pypdf import PdfReader

    reader = PdfReader(io.BytesIO(raw))
    pages = []
    for number, page in enumerate(reader.pages[:MAX_PDF_PAGES], start=1):
        text = (page.extract_text() or "").strip()
        if text:
            pages.append(f"--- עמוד {number} ---\n{text}")
    if not pages:
        # A scanned document is an image inside a PDF wrapper. Saying "empty"
        # would be misleading - there is content, it just is not text.
        return (
            "ה-PDF לא מכיל טקסט שניתן לחלץ. סביר שזה מסמך סרוק (תמונה), "
            "וקריאה שלו תדרוש OCR שלא מותקן כאן."
        )
    return "\n\n".join(pages)


_READERS = {
    ".txt": _read_plain_text, ".md": _read_plain_text, ".json": _read_plain_text,
    ".log": _read_plain_text, ".xml": _read_plain_text, ".html": _read_plain_text,
    ".csv": _read_delimited, ".tsv": _read_delimited,
    ".xlsx": _read_xlsx, ".xlsm": _read_xlsx,
    ".docx": _read_docx,
    ".pdf": _read_pdf,
}

# Named so the assistant can explain the limit instead of reporting a failure.
_KNOWN_UNSUPPORTED = {
    ".xls": "פורמט Excel ישן (xls). צריך לשמור אותו מחדש כ-xlsx כדי שאוכל לקרוא.",
    ".doc": "פורמט Word ישן (doc). צריך לשמור אותו מחדש כ-docx כדי שאוכל לקרוא.",
    ".ppt": "מצגת PowerPoint - קריאת מצגות לא נתמכת.",
    ".pptx": "מצגת PowerPoint - קריאת מצגות לא נתמכת.",
    ".zip": "קובץ ZIP - צריך לחלץ אותו קודם.",
    ".rar": "קובץ RAR - צריך לחלץ אותו קודם.",
    ".jpg": "תמונה. אני קורא טקסט בלבד, לא מנתח תמונות.",
    ".jpeg": "תמונה. אני קורא טקסט בלבד, לא מנתח תמונות.",
    ".png": "תמונה. אני קורא טקסט בלבד, לא מנתח תמונות.",
    ".heic": "תמונה. אני קורא טקסט בלבד, לא מנתח תמונות.",
    ".gif": "תמונה. אני קורא טקסט בלבד, לא מנתח תמונות.",
}


def _extension(filename: str) -> str:
    _, dot, ext = filename.rpartition(".")
    return f".{ext.lower()}" if dot else ""


def supported_extensions() -> list:
    return sorted(_READERS)


def is_supported(filename: str, mime_type: str = "") -> bool:
    """Whether extract_text can read this file, judged from its name alone.

    Needed before the bytes exist: read_email lists what is attached without
    downloading anything, and has to say which ones are worth asking for."""
    ext = _extension(filename)
    if ext in _READERS:
        return True
    if not ext and mime_type:
        return mime_type.startswith("text/") or mime_type == "application/pdf"
    return False


def extract_text(filename: str, raw: bytes, mime_type: str = "") -> str:
    """Converts one attachment's bytes to text, or explains why it cannot.

    Always returns a string - callers surface it to the user as-is, so a failure
    has to read as an explanation rather than as a stack trace or as silence."""
    if not raw:
        return "❌ הקובץ ריק."
    if len(raw) > MAX_ATTACHMENT_BYTES:
        size_mb = len(raw) / (1024 * 1024)
        return (
            f"❌ הקובץ גדול מדי לקריאה ({size_mb:.1f}MB, המגבלה "
            f"{MAX_ATTACHMENT_BYTES // (1024 * 1024)}MB)."
        )

    ext = _extension(filename)
    reader = _READERS.get(ext)

    if reader is None and not ext and mime_type:
        # No extension to go on - fall back to the declared type, which is the
        # only remaining signal.
        if mime_type.startswith("text/"):
            reader = _read_plain_text
        elif mime_type == "application/pdf":
            reader = _read_pdf

    if reader is None:
        if ext in _KNOWN_UNSUPPORTED:
            return f"❌ {_KNOWN_UNSUPPORTED[ext]}"
        return (
            f"❌ סוג הקובץ {ext or mime_type or 'לא ידוע'} אינו נתמך לקריאה. "
            f"נתמכים: {', '.join(supported_extensions())}"
        )

    try:
        text = reader(raw)
    except zipfile.BadZipFile:
        # xlsx and docx are both zip containers; a corrupted or mislabelled file
        # fails here rather than anywhere more informative.
        return "❌ הקובץ פגום או שסיומת הקובץ לא תואמת לתוכן שלו."
    except Exception as e:
        logger.error(f"Attachment parse failed for {filename!r}: {e}")
        return f"❌ לא הצלחתי לפענח את הקובץ: {e}"

    if not text.strip():
        return "הקובץ נקרא בהצלחה אך אין בו טקסט."
    return _truncate(text)
